### ISSUE TITLE
panic with v1.4.0: type cty.Type has no exported fields

### ISSUE THREAD

**Issue by maerlyn** [wata727/packer-plugin-amazon-ami-management#383]
I'm not sure if this is a bug with packer or this plugin.

I've tried it with latest packer, also version 1.8.6. Both work with version 1.3.1 of this plugin.

Here's the relevant output with the stack trace:

```
# packer version
Packer v1.9.1

# packer init .
Installed plugin github.com/wata727/amazon-ami-management v1.4.0 in "/home/ubuntu/.config/packer/plugins/github.com/wata727/amazon-ami-management/packer-plugin-amazon-ami-management_v1.4.0_x5.0_linux_amd64"

# packer build .
panic: ConfigSpec failed: gob: type cty.Type has no exported fields [recovered]
	panic: ConfigSpec failed: gob: type cty.Type has no exported fields

goroutine 1 [running]:
log.Panic({0xc000a1e2e0?, 0x0?, 0xc000a1e340?})
	log/log.go:384 +0x65
github.com/hashicorp/packer/packer.(*cmdPostProcessor).checkExit(0x416250?, {0x295cdc0, 0xc000c8cdd0}, 0x0)
	github.com/hashicorp/packer/packer/cmd_post_processor.go:50 +0x7f
github.com/hashicorp/packer/packer.(*cmdPostProcessor).ConfigSpec.func1()
	github.com/hashicorp/packer/packer/cmd_post_processor.go:22 +0x39
panic({0x295cdc0, 0xc000c8cdd0})
	runtime/panic.go:884 +0x[21](https://github.com/ingatlancom/packer/actions/runs/5375889656/jobs/9752342914#step:5:22)3
github.com/hashicorp/packer-plugin-sdk/rpc.(*commonClient).ConfigSpec(0xc000c8af00)
	github.com/hashicorp/packer-plugin-sdk@v0.4.0/rpc/common.go:47 +0x297
github.com/hashicorp/packer/packer.(*cmdPostProcessor).ConfigSpec(0xc000a1e718?)
	github.com/hashicorp/packer/packer/cmd_post_processor.go:[25](https://github.com/ingatlancom/packer/actions/runs/5375889656/jobs/9752342914#step:5:26) +0x65
github.com/hashicorp/packer/hcl2template.decodeHCL2Spec({0x38e3ba0, 0xc000649530}, 0x0?, {0x7ffa3dddcb98?, 0xc000c7f8c0?})
	github.com/hashicorp/packer/hcl2template/decode.go:20 +0x39
github.com/hashicorp/packer/hcl2template.(*HCL2PostProcessor).HCL2Prepare(0xc000c94a80, 0xc000c94a50?)
	github.com/hashicorp/packer/hcl2template/types.hcl_post-processor.go:53 +0x41c
github.com/hashicorp/packer/hcl2template.(*PackerConfig).startPostProcessor(0xc0000e43c0, {{{0xc000632e07, 0xa}, {0xc000632e12, 0xc}}, {0x0, 0x0}, {0x38e3ba0, 0xc000648000}}, 0xc000564900, ...)
	github.com/hashicorp/packer/hcl2template/types.build.post-processor.go:86 +0x5f8
github.com/hashicorp/packer/hcl2template.(*PackerConfig).getCoreBuildPostProcessors(0xc0000e43c0, {{{0xc000632e07, 0xa}, {0xc000632e12, 0xc}}, {0x0, 0x0}, {0x38e3ba0, 0xc000648000}}, {0xc0006498f0, ...}, ...)
	github.com/hashicorp/packer/hcl2template/types.packer_config.go:556 +0x3f2
github.com/hashicorp/packer/hcl2template.(*PackerConfig).GetBuilds(0xc0000e43c0, {{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, ...}, ...})
	github.com/hashicorp/packer/hcl2template/types.packer_config.go:695 +0x17f7
github.com/hashicorp/packer/command.(*BuildCommand).RunContext(0xc0001657d0, {0x38e34a0?, 0xc00015c050}, 0xc00014a090)
	github.com/hashicorp/packer/command/build.go:115 +0x2bd
github.com/hashicorp/packer/command.(*BuildCommand).Run(0xc0001657d0, {0xc0000501a0, 0x1, 0x1})
	github.com/hashicorp/packer/command/build.go:41 +0xc5
github.com/mitchellh/cli.(*CLI).Run(0xc0000e4140)
	github.com/mitchellh/cli@v1.1.2/cli.go:[26](https://github.com/ingatlancom/packer/actions/runs/5375889656/jobs/9752342914#step:5:27)2 +0x5f8
main.wrappedMain()
	github.com/hashicorp/packer/main.go:265 +0xcc5
main.realMain()
	github.com/hashicorp/packer/main.go:52 +0xf5
main.main()
	github.com/hashicorp/packer/main.go:[38](https://github.com/ingatlancom/packer/actions/runs/5375889656/jobs/9752342914#step:5:39) +0x19
```

**Comment by wata727** [comment]
Umm... Probably caused by this issue https://github.com/hashicorp/packer-plugin-sdk/issues/135

**Comment by maerlyn** [comment]
Tested it with two images, work beautifully, thank you!
